### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'test_private_list.txt'

### ISSUE THREAD

**Issue by bingws** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#10]
run data/fileList.py 

`Traceback (most recent call last):
  File "fileList.py", line 78, in <module>
    for line in fileinput.input("test_private_list.txt"):
  File "D:\ProgramData\Anaconda3\lib\fileinput.py", line 252, in __next__
    line = self._readline()
  File "D:\ProgramData\Anaconda3\lib\fileinput.py", line 364, in _readline
    self._file = open(self._filename, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: 'test_private_list.txt'`
@SoftwareGift

**Comment by SoftwareGift** [comment]
test__private_list.txt, this file contains test set labels. It is only for the organizer to reproduce our results. The label has not been released yet, so you can comment it.This has no effect on your verification results.

**Comment by bingws** [comment]
![image](https://user-images.githubusercontent.com/10806595/55786642-3edb1080-5ae7-11e9-8978-f0843b8e1fbe.png)
![image](https://user-images.githubusercontent.com/10806595/55786679-52867700-5ae7-11e9-853f-674d59636dfa.png)
I downloaded data from Baidu Cloud Disk, and did not get the results（Data index tree）that you said? What happened to this?
@SoftwareGift

**Comment by mhsszm** [comment]
the same as bingws,only have Training and Testing

**Comment by hirotong** [comment]
I wonder if we can get "test_private_list.txt" now?

**Comment by 363325971** [comment]
how do you use the "trainning" file?
