### ISSUE TITLE
Pretrained model - Google Drive

### ISSUE THREAD

**Issue by ghost** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#101]
Thank you for the project.
I read through the code and read it to run tests on them but I have problem with pretrain model.
I have finished downloading the zip file and use the password you provided to unzip.
...
But I get an error about the zip file. Am I doing something wrong? This is my error. Many thanks can someone fix them.
![Screenshot from 2021-10-11 17-00-35](https://user-images.githubusercontent.com/44012457/136772643-6fb0aebd-121a-48ab-b7a5-38d87352b614.png)

**Comment by ghost** [comment]
I have found the solution.
It's an error problem caused by the file `mobilenetv2_bs32/_6.pth.tar`. My solution is to unzip but ignore this file

![Screenshot from 2021-10-12 13-12-16](https://user-images.githubusercontent.com/44012457/136901359-df21524c-46eb-4196-a6de-a7e17d99d212.png)
e.

**Comment by JoFebriann** [comment]
hi could you provide the pretrained weights, cause the drive link seems to be down. Thank you
