### ISSUE TITLE
关于CASIA-SURF数据集

### ISSUE THREAD

**Issue by 121786404** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#2]
https://pan.baidu.com/share/init?surl=_caiA9r9SPjRI09fNKsscg  提取码：9ooz
我在这里下载了一份CASIA-SURF数据集，请问如何和
/data/2depth_train.txt
/data/2label_train.txt
/data/depth_val.txt
/data/label_val.txt
/data/depth_test.txt
/data/label_test.txt
对照起来。

**Comment by SoftwareGift** [comment]
2depth_xxx，2开头的是我们自己的数据加上官方的数据，如果只用官方的数据，可以在脚本data/fileList.py注释对应的函数，然后运行一下就可以得到file list 了。

**Comment by Guyume** [comment]
谢谢分享。

________________________________
发件人: 张鹏 <notifications@github.com>
发送时间: Saturday, March 30, 2019 3:33:35 PM
收件人: SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019
抄送: Subscribed
主题: Re: [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019] 关于CASIA-SURF数据集 (#2)


2depth_xxx，2开头的是我们自己的数据加上官方的数据，如果只用官方的数据，可以在脚本data/fileList.py注释对应的函数，然后运行一下就可以得到file list 了。

―

**Comment by pengzhaofan** [comment]
> 2depth_xxx，2开头的是我们自己的数据加上官方的数据，如果只用官方的数据，可以在脚本data/fileList.py注释对应的函数，然后运行一下就可以得到file list 了。

老板，百度网盘链接坏了

**Comment by EASY-EAI** [comment]
官方数据申请不下来 (ಥ﹏ಥ)

**Comment by 363325971** [comment]
@121786404 请问你这个里面的train文件不是图片文件，是要怎么读取呢？

**Comment by jiagh2010** [comment]
求发一份CASIA-SURF数据集，网盘那个坏了

**Comment by 363325971** [comment]
> 求发一份CASIA-SURF数据集，网盘那个坏了

没坏吧

**Comment by lrain-CN** [comment]
> 
> 
> https://pan.baidu.com/share/init?surl=_caiA9r9SPjRI09fNKsscg 提取码：9ooz
> 我在这里下载了一份CASIA-SURF数据集，请问如何和
> /data/2depth_train.txt
> /data/2label_train.txt
> /data/depth_val.txt
> /data/label_val.txt
> /data/depth_test.txt
> /data/label_test.txt
> 对照起来。

这里下的训练数据 人脸不是完整的嘛 只有眼睛部分？

**Comment by huazai-1994** [comment]
@121786404 那个百度云数据中只有眼睛部分啊，是不是不完整的？

**Comment by Galaxy-yyyyy** [comment]
请问在哪可以下载验证集了，急用！！！

**Comment by liujingcs** [comment]
你好，请问下深度图的raw data是怎么转换成RGB图的呢？Raw data的取值范围是(0~65535），RGB是（0~255）

**Comment by uniyushu** [comment]
这个数据集不全，training set只有一只眼睛，test set还少了一部分。

**Comment by sangtv9** [comment]
> 你好，请问下深度图的raw data是怎么转换成RGB图的呢？Raw data的取值范围是(0~65535），RGB是（0~255）

Have you known how to convert image range from (0, 65535) to (0,255)?? Thanks

**Comment by lawo123** [comment]
> 度图的raw data是怎么转换成RGB图的呢

我也想问这个问题，请问你现在知道怎么转换的了吗？

**Comment by oxygenman** [comment]
> 你好，请问下深度图的raw data是怎么转换成RGB图的呢？Raw data的取值范围是(0~65535），RGB是（0~255）

请问您知道怎么转换了吗？
