### ISSUE TITLE
关于使用FeatherNetB训练出错

### ISSUE THREAD

**Issue by platoTao** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#23]
我使用命令行
python main.py --config="cfgs/FeatherNetB-32.yaml" --b 32 --lr 0.01  --every-decay 60 --fl-gamma 3 >> MobileLiteNetB-bs32--train.log
但是得到如下报错
Traceback (most recent call last):
  File "main.py", line 406, in <module>
    main()
  File "main.py", line 113, in main
    model = models.__dict__[args.arch]()
  File "/home/plato/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019-regression/models/FeatherNet.py", line 161, in FeatherNetB
    model = FeatherNet(se = True,avgdown=True)
  File "/home/plato/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019-regression/models/FeatherNet.py", line 87, in __init__
    super(MobileLiteNet, self).__init__()
NameError: name 'MobileLiteNet' is not defined

请问应该怎么修改？

**Comment by platoTao** [comment]
我把 super(MobileLiteNet, self).__init__() 修改为 super(FeatherNet, self).__init__() 可以成功运行。

**Comment by 363325971** [comment]
@platoTao 我从百度云上下的数据集中的Traing.tar文件解压后就是个单独的Training文件，，这个文件是要怎么读取训练呢？

**Comment by platoTao** [comment]
@363325971  把后缀改为rar格式，然后解压

**Comment by smartwell** [comment]
> @platoTao 我从百度云上下的数据集中的Traing.tar文件解压后就是个单独的Training文件，，这个文件是要怎么读取训练呢？

你好，你能分享一下数据集吗，万分感谢，到处下不到数据

**Comment by platoTao** [comment]
把后缀改为rar格式，然后解压

**Comment by platoTao** [comment]
@smartwell  把后缀改为rar格式，然后解压。

**Comment by xjhjinhui** [comment]
> 我把 super(MobileLiteNet, self).**init**() 修改为 super(FeatherNet, self).**init**() 可以成功运行。

您好，我按照您的方法改了以后发现
FileNotFoundError: [Errno 2] No such file or directory: '/home/tay/Videos/Anti-spoofing/FeatherNets/data/Training/real_part/CLKJ_BS0125/real.rssdk/depth/151.jpg'
这个错误，我查找了一下Traning文件夹发现确实没有这个文件，这个文件好像是作者的私有数据集下的，请问您是如何开始训练的呢？
