### ISSUE TITLE
How to train about the 6 Train FeatherNetB?

### ISSUE THREAD

**Issue by TianSong1991** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#3]
Hi @SoftwareGift ,thanks for your great project! I train your model about `python3 main.py --config="cfgs/mobilenetv2.yaml" --b 8 --lr 0.001 --every-decay 40 --fl-gamma 2 >> mobilenetv2-bs32-train.log ` and I obtain more than 95% accuracy. That a small problem, I should mkdir logs file first. But I want to train your best result model, when I use your 6th train method. I use `python3 main.py --config="cfgs/FeatherNetB-32.yaml" --b 32 --lr 0.01  --every-decay 60 --fl-gamma 3 >> MobileLiteNetB-bs32--train.log` error appears.The feedback is 

> main.py:91: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   config = yaml.load(f)
> Traceback (most recent call last):
>   File "main.py", line 406, in <module>
>     main()
>   File "main.py", line 113, in main
>     model = models.__dict__[args.arch]()
> KeyError: 'FeatherNetB'

I don't know how to fix the FeatherNetB. Please help how to train the FeatherNetB correctly.Thank you.

**Comment by SoftwareGift** [comment]
I fix this error by change the network's name in the /models/FeatherNet.py and models/MobileLiteNet.py.
Thanks.

**Comment by TianSong1991** [comment]
Thank you. It worked!
