### ISSUE TITLE
How to set ColorAugmentation() for single channel near-infrared image?

### ISSUE THREAD

**Issue by eeric** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#7]
in ColorAugmentation(), in data_aug.py,
How to set  self.eig_val and self.eig_vec for single channel near-infrared image?

**Comment by SoftwareGift** [comment]
Is the near-infrared image provided by CASIA-SURF only one channel? In the competition, the near-infrared images have three channels.

**Comment by SoftwareGift** [comment]
Otherwise, you can delete ColorAugmentation(). It has little effect.

**Comment by eeric** [comment]
ok, one channel was fit to embedded machine.
