### ISSUE TITLE
Could you please tell me the password of the training data

### ISSUE THREAD

**Issue by EliasCai** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#8]
Hi, thank you for your sharing, i have download the data from baidu, but it look like need a password to unzip, could you please tell me?

**Comment by EliasCai** [comment]
i am sorry make a mistake, it no need a password

**Comment by Edwardmark** [comment]
@EliasCai Can you give a link to download the data? I cannot find it. Thanks.
