### ISSUE TITLE
请教一下用realsense采集的IR数据的预处理思路

### ISSUE THREAD

**Issue by StaringWhere** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#90]
作者您好，我用D415采集color,ir和depth数据，按照CASIA-SURF的论文里描述的那样，对齐后用Dlib和PRNet检测和裁切人脸。测试的结果是Depth准确率不错，但是IR的结果很不理想，开不开Laser我都试了下。看到你们也作了自己的数据集，请教一下用realsense采集的IR数据的预处理思路，感谢！
网络：FeatherNetB_bs32-ir
模型：googledrive里的_54.pth.tar

**Comment by StaringWhere** [comment]
大家是怎么处理数据的阿

**Comment by StaringWhere** [comment]
打开auto exposure和auto white balance让结果稳定了很多，不过感觉受光线影响还是很飘

**Comment by nghiabka** [comment]
> 作者您好，我用D415采集color,ir和depth数据，按照CASIA-SURF的论文里描述的那样，对齐后用Dlib和PRNet检测和裁切人脸。测试的结果是Depth准确率不错，但是IR的结果很不理想，开不开Laser我都试了下。看到你们也作了自己的数据集，请教一下用realsense采集的IR数据的预处理思路，感谢！
> 网络：FeatherNetB_bs32-ir
> 模型：googledrive里的_54.pth.tar

Hi , depth image and ir image in casia-surf dataset have three channels, How do you convert depth image, ir image captured from d415 to three channels?
